### PR TITLE
Add osx app

### PR DESCRIPTION
**Pull request by rayosborn**
This switch ensures that the package is built as an OSX app, which ensures the menus are accessible on launch. I believe that the switch is ignored in other systems.

### CODE REVIEW

**Comment by rayosborn** [comment]
There is not much documentation of the `osx_is_app` option, but it is essential to a OS X application launching with all the menu items accessible. Otherwise, it is necessary to click outside the window and then back in again. When I first created Conda builds, it was necessary to remove the option when building on other systems, but according to conda/conda-build#7, that should no longer be necessary, although I haven't tested it.

**Comment by tschoonj** [comment]
Hi @rayosborn 

Did a quick build on my iMac and it seems to work, since an item with the NX logo is added to the dock, but I still need to click once outside the app before the menubar becomes sensitive. I guess this is a bug in (Py)Qt?

**Comment by tschoonj** [comment]
Problem fixed!

I opened a PR in nexpy/nexpy as well.

**Comment by rayosborn** [comment]
That's great. Thanks for finding the solution - it's been bugging me for years, but I had assumed that it was an inevitable problem with how the package was built, not the PyQt code itself. I confirmed that it works on my Mac as well, so I guess it means that the `osx_is_app` switch is unnecessary. The only problem is that, while conda allows new builds without changing the version number, PyPi does not. I guess that we can merge this, and I will issue 0.12.1 in the next few days.

**Comment by tschoonj** [comment]
Sounds good.

**Comment by rayosborn** [comment]
@tschoonj, I am a little confused about the package status. There is a new build, numbered 1, but it was created over 12 hours ago around the time I submitted my PR, but a new build has not been created since we merged the PR with your fix a couple of hours ago. There are no new files in the conda-forge/nexpy directory on Anaconda.org. Do we have to do something to trigger another build?

**Comment by tschoonj** [comment]
Yeah, you're right, something strange is going on. Best to open a PR with just a version bump.

**Comment by rayosborn** [comment]
I will release v0.12.1 on PyPi with the toolbar fix after I've tested that it doesn't cause any problems on Linux. Then I presume the automated system will issue another PR.

**Pull request merged**
